FROM nginx:alpine

# Copy config
COPY nginx.cloud.conf /etc/nginx/conf.d/default.conf

# Copy frontend files directly into the image
COPY ./frontend /usr/share/nginx/html

# Create the directory where we will mount the bucket
RUN mkdir -p /usr/share/nginx/html/temp-audio