FROM python:3.11-slim

WORKDIR /code

RUN pip install uv

COPY pyproject.toml uv.lock* ./

ENV UV_HTTP_TIMEOUT=300

RUN uv sync --frozen --no-dev

RUN python -m nltk.downloader stopwords

COPY . ./server
